### ISSUE TITLE
Git commit user is unknown

### ISSUE THREAD

**Issue by k0shk0sh** [afollestad/aesthetic#1]
Hey buddy, can't wait to see what it is.

Noticed that your commits are from unknown I guess you shifted to new pc/laptop? 

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by afollestad** [comment]
My work computer uses a different SSH key.

**Comment by k0shk0sh** [comment]
@afollestad owh, I thought its not intentional. 
Thanks for the quick reply

_Sent from my Htc m8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
