### ISSUE TITLE
Local compilation issues with AppCompat

### ISSUE THREAD

**Issue by heinzan** [afollestad/aesthetic#100]
C:/Users/Lenovo/.gradle/caches/transforms-1/files-1.1/appcompat-1.0.0-rc02.aar/0cabb234390af3a165f5f84b87e85d05/res/values-v28/values-v28.xml |  
-- | --
error: resource android:attr/dialogCornerRadius not found. |  
-- | --
C:/Users/Lenovo/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/aba0f96ffc86c139dffc826e99e8d7ee/res/values/values.xml |  
-- | --

error: resource android:attr/fontVariationSettings not found. |  
-- | --
error: resource android:attr/ttcIndex not found. |  

This Error occur when i add 
    implementation 'com.afollestad:aesthetic:0.7.1' at gradle
Please help me

**Comment by afollestad** [comment]
Your app needs to be using AndroidX rather than the Support Library, and Kotlin 1.2.70.
