### ISSUE TITLE
Request: Add the ability to add custom InflationInterceptors

### ISSUE THREAD

**Issue by gonemad** [afollestad/aesthetic#106]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/aesthetic/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have verified that I am using the latest version of Aesthetic (see the README).
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/aesthetic/blob/master/README.md) (before asking questions on how to do something).

---

It would be nice if there was a way to set a custom InflationInterceptor.  I have some third party UI components that I would like to theme the same way as all the regular android widgets.  Right now I have to clone a local copy of aesthetic and add my aesthetic versions of the these 3rd party UI components.

**Comment by afollestad** [comment]
https://github.com/afollestad/aesthetic/releases/tag/1.0.0-beta01
