### ISSUE TITLE
Ability to disable NavigationView icon tinting

### ISSUE THREAD

**Issue by gautam2682** [afollestad/aesthetic#107]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/aesthetic/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have verified that I am using the latest version of Aesthetic (see the README).
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/aesthetic/blob/master/README.md) (before asking questions on how to do something).

---

**If this is a feature request, you can clear everything below.**

I want to show original icon colors in drawer layout but cannot apply  `navigationView?.itemIconTintList = null` as this is masked by  library and i have also tried       `android:tag=":aesthetic_ignore"` everywhere but its not affecting it also i tried to set itemIconTintList null in the library itself but same result . please help it will be very hepful, Btw awesome library.)

**Comment by gautam2682** [comment]
I tried `NavigationViewMode.NONE` but it is still not showing showing original colors while by Appcompatactivity it is showing original color, please check one more time and thanks for the help , my configuration is this:-
 ```
  Aesthetic.config {
            isDark(false)
            colorPrimaryRes(android.R.color.white)
            colorAccentRes(R.color.red500)
            colorStatusBarAuto()
            textColorPrimaryRes(android.R.color.black)
            textColorSecondaryRes(android.R.color.black)
            navigationViewMode(NavigationViewMode.NONE)
        }
```
And i am using   ` navigationView?.itemIconTintList = null` later in the activity to disable tint

**Comment by afollestad** [comment]
Oh I found the problem - `NavigationView` items are actually instances of `CheckedTextView`, so it's getting overridden there. Will fix 😄

**Comment by gautam2682** [comment]
Thank you😊😊
