### ISSUE TITLE
when update version this error occur Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 

### ISSUE THREAD

**Issue by heinzan** [afollestad/aesthetic#116]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [ ] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/aesthetic/issues?q=is%3Aissue+is%3Aclosed)
- [ ] I have verified that I am using the latest version of Aesthetic (see the README).
- [ ] I have given my issue a non-generic title.
- [ ] I have [read over the documentation](https://github.com/afollestad/aesthetic/blob/master/README.md) (before asking questions on how to do something).

---

**If this is a feature request, you can clear everything below.**

##### Include the following:

 - Affected device(s): Google Pixel 2 XL, Android 9

Also, please wrap your code with correct syntax highlighting (not just indents).

```kotlin
println("Hello, world!")
```

```xml
<LinearLayout ...></LinearLayout>
```
 
---

**Comment by heinzan** [comment]
i updated from  implementation 'com.afollestad:aesthetic:0.4.7' to implementation 'com.afollestad:aesthetic:1.0.0-beta04' and 0.7.2 error occur.This is my gradle 
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    minSdkVersion 19
        targetSdkVersion 28
        multiDexEnabled true

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

**Comment by afollestad** [comment]
Your app needs to use AndroidX instead of the Support Library.

**Comment by heinzan** [comment]
i cann't use androidX because another libraryies will conflict.Pls show another way bro.Thanks

**Comment by afollestad** [comment]
I don't know any other way. You'll have to stick to older versions of aesthetic.

**Comment by afollestad** [comment]
You're probably using a different version of the Support library than that version of Aesthetic.

**Comment by afollestad** [comment]
Actually the last version of Aesthetic that did not is AndroidX is older than 0.7.x

https://github.com/afollestad/aesthetic/releases

Otherwise, I'm not sure what else could be a problem.

**Comment by heinzan** [comment]
Thanks bro.
