### ISSUE TITLE
Sample.apk fails to install

### ISSUE THREAD

**Issue by MasoodFallahpoor** [afollestad/aesthetic#12]
I downloaded the sample.apk file to install it on my device using ADB but it failed with the following error:
INSTALL_PARSE_FAILED_NO_CERTIFICATES
Is it properly signed with a release key?

**Comment by afollestad** [comment]
Hmm, that's weird. Yeah, a keystore is used to sign it.

**Comment by afollestad** [comment]
Added a new APK which isn't signed at all. A debug APK should install just fine.
