### ISSUE TITLE
Migrate to RxJava 2

### ISSUE THREAD

**Issue by MasoodFallahpoor** [afollestad/aesthetic#14]
If someone uses Aesthetic in a app which is already using RxJava (version 2.x) the project fails to build with an error more or less like the following:
```bash
More than one file was found with OS independent path 'META-INF/rxjava.properties'
```
I think it's a good idea to mention it in README and provide its solution.
```groovy
android {
    ...
    packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }
}
```

**Comment by afollestad** [comment]
Migrated to RxJava 2 in 0.4.0
