### ISSUE TITLE
Snackbar theming

### ISSUE THREAD

**Issue by shahidshaikhs** [afollestad/aesthetic#16]
I didn't find any examples on how to set text colors for these two attributes. 

![screenshot_20170518-140328 01](https://cloud.githubusercontent.com/assets/11992755/26193492/17e97a5a-3bd3-11e7-9f1b-cfd129f73465.png)

**Comment by afollestad** [comment]
Hmm, well toasts aren't themable on purpose. The text should always be white (the library doesn't touch them).

I'll look at Snackbars though.

**Comment by afollestad** [comment]
I've implemented [Snackbar support](https://github.com/afollestad/aesthetic#snackbars) in 0.3.2.

There are definitely no issues with toasts, unless you're using an old version of this lib.
![affix_20170518_120810](https://cloud.githubusercontent.com/assets/1820165/26214810/5cb4a868-3bc3-11e7-9be3-9afcadfe1b20.png)

**Comment by shahidshaikhs** [comment]
Thank you for looking into it :)
