### ISSUE TITLE
Activities should recreate on return if activityTheme has changed 

### ISSUE THREAD

**Issue by boswelja** [afollestad/aesthetic#23]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.4`
 - Device OS version: `7.1.2+`
 - Device: Any

###### Reproduction Steps
Launch separate settings activity
Toggle dark mode
Go back to main activity

###### Expected Result
Activity is recreated, everything themed properly

###### Actual Result
TabLayout text hasn't changed
MaterialDrawer background hasn't changed (https://github.com/mikepenz/MaterialDrawer)
Probably more

**Comment by afollestad** [comment]
Fixed in 0.4.5
