### ISSUE TITLE
colorCardViewBackgroundRes() only works when CardView color is previously defined in XML

### ISSUE THREAD

**Issue by HugoCastelani** [afollestad/aesthetic#24]
I realized that `colorCardViewBackgroundRes()` only works when I previously set any color via XML with `app:cardBackgroundColor`, then the method override this value and set the one specified in its parameters. 

PS.: happens with a RecyclerView item, don't know if it proceeds with pre-positioned CardViews.

**Comment by afollestad** [comment]
Fixed in 0.4.6
