### ISSUE TITLE
Background subscriptions cause memory leaks due to View references

### ISSUE THREAD

**Issue by MasoodFallahpoor** [afollestad/aesthetic#25]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

 - Aesthetic version: `0.4.6`
 - Device OS version: `6.0`
 - Device Name: `Any`

I'm using LeakCanary to detect memory leaks and it constantly nags about memory leaks in almost all activities that extend AestheticActivity. In all these memory leaks LeakCanary reports something like

![Screenshot of memory leak](https://cloud.githubusercontent.com/assets/8100951/26339007/04b56ece-3f9a-11e7-91bf-876531b45ab8.png)

PS: Top 3 lines are always the same

**Comment by afollestad** [comment]
0.4.7 should improve this if not fix it

https://github.com/afollestad/aesthetic/releases/tag/0.4.7

**Comment by MasoodFallahpoor** [comment]
After updating to 0.4.7 the number of leaks reduced significantly but there are still leaks.
![untitled](https://cloud.githubusercontent.com/assets/8100951/26388053/5ab830b8-4067-11e7-8033-303d3ed91bc1.png)
![untitled1](https://cloud.githubusercontent.com/assets/8100951/26388054/5ab8e878-4067-11e7-87ae-3852a480f6ec.png)

**Comment by timusus** [comment]
I believe the source for a lot of these leaks is the following code in `InflationInterceptor`:
```
if (viewBackgroundRes != 0) {
  Observable<Integer> obs;
  obs = ViewUtil.getObservableForResId(view.getContext(), viewBackgroundRes, null);
  if (obs != null) {
    Aesthetic.get().addBackgroundSubscriber(view, obs);
  }
}
```

Any `View` which uses one of the automatically-themed `viewBackgroundRes` resources for its background ends up becoming part of a `ViewBackgroundSubscriber`, which subscribes to color change events for the source `colorObservable`. These subscriptions are only removed in `activity.isFinishing()`.

If my understanding is correct, `Views` belonging to `Fragments` that have been created and destroyed throughout the lifetime of an `Activity` will leak until the `Activity` is destroyed.

~~Maybe `Fragments` could pass some lifecycle events (`onCreateView/onDestroyView`) to `Aesthetic` (via a base `AestheticFragment` class), and `Aesthetic` could query its `backgroundSubscriberViews`. In `onDestroyView`,  we'd remove any `View` that returns false for `isAttachedToWindow()`. I'm not sure how we'd go about ensuring automatically-themed views resubscribe for theming though, once they've been removed from `backgroundSubscriberViews`.~~
Nevermind, this would just cause views to stop auto-theming if they weren't being displayed when any fragment is destroyed. I don't really have any ideas about how to tackle this issue. 

The only solid solution I can think of, is removing automatic-theming of `Views`, and requiring any `View` that wants to be themed to inherit from some `Aesthetic` variant which properly unsubscribes when detached from the window.

**Comment by timusus** [comment]
Based on my investigation above, I'd actually recommend removing automatic theming of background views in Aesthetic. It makes the library slightly less user-friendly, as you don't get automatic theming out of the box, but it prevents leaking views throughout your app, which is much more important. 

I'm using Aesthetic extensively throughout an app of mine, and removing automatic background theming really wasn't much hassle. I just had to re-implement a few `Disposables` to theme some particular elements - most of the theming is done by existing `Aesthetic`-subclassed `Views`.

**Comment by boswelja** [comment]
Yes, if we remove automatic theming, there won't be much extra work users need to do to have themed views, and as a bonus, app start times should be quicker

**Comment by boswelja** [comment]
To add to the topic of removing automatic theming, we could keep 2 different versions. The easy-to-use version with auto-theming - good for testing, and the non-auto theming version which would have better performance / smaller apk but takes longer to implement properly.
We could also have community-maintained compatibility plugins that adds aesthetic-themed views for different libraries, so we don't keep getting requests for "theme x library" without auto-theming

**Comment by timusus** [comment]
I think you might be misunderstanding where I'm suggesting this leak is coming from. It's not in the 'automatic theming' provided by `AestheticXView` subclasses that is causing a leak, but rather the `backgroundSubscriberViews` added in `Aesthetic.addBackgroundSubscriber()`, called in `InflationInterceptor`, for non `Aesthetic`-subclassed view background theming.

Not that removing this feature is necessarily the best solution, but I don't think it's a good idea to retain leaking code just for ease-of-use. I also don't think that non-auto theming results in a significantly (if at all) smaller apk, and the prospect of maintaining two forks of this library at this early stage doesn't really appeal to me. 

I do like the idea of compatibility plugins for various views though, I think that's a great idea.

**Comment by boswelja** [comment]
Yes, what I mean by removing automatic theming is removing the InflationInterceptor, and requiring the user to use / extend Aesthetic views, or add support in their custom views

**Comment by timusus** [comment]
I'm not sure what the purpose of that would be? That would severely diminish the usefulness of Aesthetic in my opinion.

**Comment by afollestad** [comment]
Removing inflation interception would defeat the purpose of this library, it's the foundation.

**Comment by boswelja** [comment]
Isn't the InflationInterceptor only used to auto detect / theme views?

**Comment by afollestad** [comment]
It's the base of the library. It replaces views with other view types at runtime.

The background theming thing is separate.

**Comment by afollestad** [comment]
E.g. `TextView` gets replaced with `AestheticTextView` during inflation.

**Comment by boswelja** [comment]
It's my understanding that if we remove the InflationInterceptor and require users to use / extend Aesthetic views, we won't have memory leaks? I also think removing the InflationInterceptor will improve startup times

**Comment by afollestad** [comment]
No, the inflation interceptor does not hold any references. The background theming mechanism does, which is only used on views which are *not* handled by the interceptor.

Google's AppCompat uses inflation interceptor to replace `TextView` with `AppCompatTextView`, `ImageView` with `AppCompatImageView`, etc.

**Comment by afollestad** [comment]
To be more specific, the code here which adds the view to a global static map if it doesn't not get handled above.

https://github.com/afollestad/aesthetic/blob/master/library/src/main/java/com/afollestad/aesthetic/InflationInterceptor.java#L302
