### ISSUE TITLE
Missing colorPrimaryDark property

### ISSUE THREAD

**Issue by MFlisar** [afollestad/aesthetic#26]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.6`

###### Reproduction Steps

1. There is no getter/setter for primary dark color
2. BottomNavigationView background is not themed, it uses the `app:itemBackground` setting

###### Expected Result

1. I would expect it to be there as it's the third main material color
2. I would expect that the `app:itemBackground` is checked and replaced as well

**Comment by afollestad** [comment]
It's provided directly as the status bar color in this library currently.

**Comment by afollestad** [comment]
Also, there is `BottomNavigationView` support. You have to set the background color to an attribute if you wish it to be something that isn't gray or white. Have your read over the tutorial or looked at the sample project?

**Comment by afollestad** [comment]
Separated `colorPrimaryDark` and `colorStatusBar` in 0.4.7.

https://github.com/afollestad/aesthetic/releases/tag/0.4.7
