### ISSUE TITLE
Inherited views are not supported

### ISSUE THREAD

**Issue by MFlisar** [afollestad/aesthetic#27]
- [ x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ x] I have verified that I am using the latest version of Aesthetic (see the README)
- [ x] I have given my issue description title
- [ x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.6`
 
###### Reproduction Steps

Create a custom view, i.e. a class like `ExtendedSwitch extends Switch` and use it

###### Expected Result

I would expect that all custom views are themed the same way as the base view would be

###### Actual Result

Nothin happens

**Comment by afollestad** [comment]
See the README. There was also a duplicate issue.
