### ISSUE TITLE
ContextMenu headers don't get themed

### ISSUE THREAD

**Issue by boswelja** [afollestad/aesthetic#29]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.7`
 - Device OS version: `7.1.2+`
 - Device: any

###### Reproduction Steps
Open a context menu

###### Expected Result
Themed, nice looking

###### Actual Result
Context menu with default theme and light coloring

**Comment by boswelja** [comment]
On launching my app, the backgrounds for menus, and the nav drawer (using MaterialDrawers) are the default (white), but if I toggle dark mode, it recreates the activity and it's fixed. Context menu title isnt colored with the accent color at all :(

**Comment by afollestad** [comment]
Context menus as in overflow menus?

**Comment by boswelja** [comment]
Basically, it's the long press menu, it can be seen on long pressing a WiFi network in settings too

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by boswelja** [comment]
The main issue is the header text color doesn't change with the accent color, so it stays with the apps default accent

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by afollestad** [comment]
Oh, yeah, `PopupMenu`'s.

I've never seen headers in a popup menu 😁

**Comment by boswelja** [comment]
Do you think it's fixable? ContextMenus are programmatically created, so we probably cannot hook it with LayoutInflater

**Comment by afollestad** [comment]
Internally, it appears `PopupMenu`'s do use inflation

http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.0.1_r1/com/android/internal/view/menu/MenuPopupHelper.java#340

**Comment by afollestad** [comment]
How are you you able to show a header in a `PopupMenu`? Is there something you can do with a `group` in the menu XML?

**Comment by afollestad** [comment]
There doesn't appear to be header support in `PopupMenu`'s, I'm guessing Google just has a non-clickable `MenuItem` in there which uses a custom view to color itself

**Comment by afollestad** [comment]
For the background theming, the activity theme should be all that's needed for that.

**Comment by boswelja** [comment]
Because it's a ContextMenu class, not a PopupMenu. I've just found a way for me to use a custom layout file for the header, maybe that will work

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by boswelja** [comment]
Yeah, the background changes with the activity, is just the header text color they doesn't

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by afollestad** [comment]
Oh I didn't know anyone still used that class lol

**Comment by boswelja** [comment]
👏 
It's not deprecated, and imo is better to use in lists as I don't need to repeat the overflow drawable on each item.

**Comment by boswelja** [comment]
🤔 
May not need to change context menus, I'm considering swapping them out for overflow actions again and making a Contextual ActionBar for multi-select actions

**Comment by boswelja** [comment]
OK so I have found a workaround.. I can change the color of the header text by converting Aesthetics accent color to a hex value, wrapping the text in HTML font & color tags and running it through Html.fromHtml(). Whether or not you want to leave this open or not is up to you @afollestad

**Comment by boswelja** [comment]
I use the following string resource and format it programmatically with my color (converted to #RRGGBB), and then the text I want colored
`<string name="color_text"><![CDATA[<font color="%1$s">%2$s</font>]]></string>`
