### ISSUE TITLE
Crash when a CoordinatorLayout does not contain a Collapsing Toolbar Layout

### ISSUE THREAD

**Issue by HugoCastelani** [afollestad/aesthetic#3]
@afollestad, first of all, congratulations on another amazing library.

I tested with several layouts but had problems only with the aforementioned. By the way, I simplified the layout to make logcat small. Follow the attached file.

[logcat.txt](https://github.com/afollestad/aesthetic/files/999000/logcat.txt)

**Comment by afollestad** [comment]
It's not that it's unsupported, in fact there's a section for it in the README. Looks like there's a specific though, thanks.

**Comment by afollestad** [comment]
The crash is now resolved in release 0.0.5

**Comment by HugoCastelani** [comment]
Nice work.
