### ISSUE TITLE
ActionMenuItemView title briefly visible when inflating new menu

### ISSUE THREAD

**Issue by timusus** [afollestad/aesthetic#30]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

 - Aesthetic version: `0.4.7`
 - Device OS version: `7.1.2`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps

When switching between pages, for example in a `FragmentViewPager`, if the individual `Fragments` inflate their own `Menus` (via `toolbar.setMenu()`) the `MenuItem's` text can be seen, before the icon is shown. This is best described as a 'flicker' when changing menus. Most obvious or perhaps only replicated if the `MenuItems` actually differ between the two `Fragments`.

See below:
![aesthetic-menu-bug](https://cloud.githubusercontent.com/assets/4422616/26401300/9532736e-40c8-11e7-957c-69f4b80d74e2.gif)

Note: The text displays for slightly longer than it seems in the gif, looks like a few frames were skipped.

###### Expected Result

The `MenuItem` text should not 'flash' on the screen before the icon is shown.

###### Additional

I've identified the source of this bug, see the following PR:

https://github.com/afollestad/aesthetic/pull/31

**Comment by xdk78** [comment]
I the same issue in my app
