### ISSUE TITLE
issue importing

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [afollestad/aesthetic#33]
I get this:

Error:Execution failed for task ':library:prepareComAndroidSupportAnimatedVectorDrawable2531Library'.
> Could not initialize class com.android.ide.common.util.ReadWriteProcessLock

![image](https://cloud.githubusercontent.com/assets/5357526/26523089/e76638c2-4317-11e7-96b2-94f5612ddef3.png)

**Comment by boswelja** [comment]
What is your build.gradle like? Have you tried to invalidate caches and restart?

**Comment by AndroidDeveloperLB** [comment]
These are the gradle files:
![image](https://cloud.githubusercontent.com/assets/5357526/26524594/014a6140-4341-11e7-90fb-e9df19d27b57.png)

I have tried to invalidate the cache and restart. 
For some reason, it works now. How come?

**Comment by boswelja** [comment]
Invalidate caches fixes most issues. If it doesn't, you may need to report it as it is probably a project issue

**Comment by AndroidDeveloperLB** [comment]
ok thanks
