### ISSUE TITLE
Support for MaterialDialog

### ISSUE THREAD

**Issue by timusus** [afollestad/aesthetic#36]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

 - Aesthetic version: `0.4.7`

Just wondering if there's a simple/clever way to theme `MaterialDialogs`. Figured I may as well ask as you wrote both libraries ;)

The trouble I have is implementing it in a reactive way - dialogs are usually created and shown synchronously, and I'd rather not call `Aesthetic.get().toBlocking()` to retrieve the required colors, as it makes the reactive aspect of the library pointless, and could potentially block the main thread.

I guess I could wrap the `MaterialDialog.Builder` in an `Observable<Builder>` and theme it before emitting the `Builder`, but I'm reluctant to RX-ify all of the code using Dialogs throughout the app - there is a hell of a lot.

**Comment by afollestad** [comment]
There's actually a class in Material Dialogs that you can use to set global theming colors at runtime: https://github.com/afollestad/material-dialogs/blob/master/core/src/main/java/com/afollestad/materialdialogs/internal/ThemeSingleton.java

The Color Chooser Dialog in the MD sample project actually uses it.

I could integrate it into this library when I have some time, but you could subscribe to theme color changes and update the singleton fields from that.

**Comment by timusus** [comment]
No worries, I'll do just that.

You can probably close this one - it's not reasonable to expect Aesthetic to cover theming of any and all 3rd party libraries.
