### ISSUE TITLE
Suggestion: add support for custom Attributes

### ISSUE THREAD

**Issue by jordyamc** [afollestad/aesthetic#40]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of Aesthetic (see the README)
- [X] I have given my issue description title
- [X] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.6`
 - Device OS version: `7.0.0`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto G5 Plus`
 
###### Reproduction Steps
Apply any theme colors

###### Expected Result
Material Drawer library change whith the colors given

###### Actual Result
Material Drawer library change whith Default values

I think is because the library uses custom attibutes for customization

Library:
https://github.com/mikepenz/MaterialDrawer

**Comment by boswelja** [comment]
I fixed this by subscribing to the color I wanted and updating the drawer items manually

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jordyamc** [comment]
But its not only the items, the background and header text color change to default

**Comment by boswelja** [comment]
Do your themes extend MaterialDrawerTheme? I don't have any problems with background and text color

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jordyamc** [comment]
Yes, the problem is that the default background color Is white, but my app use 2 variants, one "ligth" with white background, and one "dark" with mayor customization of the colors (the style that fails the most), and when i use the library all the customization go go default

**Comment by boswelja** [comment]
I see..

**Comment by afollestad** [comment]
I can't support every third-party library, so it's best if you subscribe to theme properties and update MaterialDrawer from there.
