### ISSUE TITLE
Button background not tinted in re-generated fragment in ViewPager

### ISSUE THREAD

**Issue by wenris** [afollestad/aesthetic#43]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.x.x.x`
 - Device OS version: `0.4.7`
 - Device Manufacturer: `Google`
 - Device Name: `Nexus 5X`

###### Reproduction Steps

1. In the sample app, add one more Fragment
2. Swipe to the third page, then back to the first page
3. Background of buttons in the first page were not tinted

I have checked that when `MainPagerAdapter::getItem(int position)` is recalled, buttons in the re-generated view will not be tinted.

![gif](https://user-images.githubusercontent.com/11177691/27515051-4144a9b6-59cd-11e7-8d7b-13e759c419d0.gif)

**Comment by boswelja** [comment]
I have the same issue with the AboutLibraries plugin.. Buttons aren't colored, but tapping them causes them to be colored

**Comment by wenris** [comment]
It seems that only when the state was changed did the background change.
Add the following piece of code at the end of `AestheticButton::invalidateColors` works:
```java
  private void invalidateColors(ColorIsDarkState state) {
    ...
    setEnabled(!isEnabled());
    setEnabled(!isEnabled());
  }
```

REF: https://stackoverflow.com/questions/36114388/setbackgroundtintlist-does-not-apply-directly#comment59871614_36114388.

**Comment by garydonmills** [comment]
I am using your library to theme a project I am working on.  I am loving how easy it is to use.  Previously, on a former project, I created my own theme engine and it was a nightmare to get it to work correctly.  So I thoroughly appreciate the hard work that has been put into this.

I am having this same issue with button color not showing after fragment recreation.  I am not using a ViewPager, however.  I am using only fragments and navigation view.

I am also having an issue with progress bar horizontals.  The library seems to be overriding and making the progress bar be the default circular pattern.

I suppose that until I can figure out how to fix these two issues, I will release the app without this great library.  I will continue to play around with this library.  I do really like it.  Keep up the great work!

Thanks again!
