### ISSUE TITLE
Grey text color for both: title and summary in Settings with Aesthetic

### ISSUE THREAD

**Issue by MenosGrante** [afollestad/aesthetic#48]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.7`
 - Device OS version: `7.1.2 (Lineage OS)`
 - Device Manufacturer: `Google`
 - Device Name: `Nexus 5`
 
###### Reproduction Steps
- Include Aesthetic in your project;
- Done!

###### Expected Result
- Black color for titles;
- Grey color for summaries.

###### Actual Result
- Grey color for both.

![screenshot_20170701-165758](https://user-images.githubusercontent.com/2765109/27762617-7783a292-5e7e-11e7-8e74-d38f2d34ea31.png)

**Comment by boswelja** [comment]
I'm looking into it now, but I'm pretty sure aesthetic is just coloring all the text with the secondary text color
