### ISSUE TITLE
Make transition between activityTheme changes smoother

### ISSUE THREAD

**Issue by jahirfiquitiva** [afollestad/aesthetic#5]
[Here's a video](https://drive.google.com/file/d/0Bw52d3_ZiSb9SWJaWEw3SUYzMEU/view?usp=sharing). Also, for a split of a second, one can see the default light with teal accent theme.

Thanks

**Comment by afollestad** [comment]
Well, the Activity recreates itself, so that's kind of unavoidable. 

The best solution you could use in your own apps would be an Activity enter/exit fade animation (like what Twitter uses when you toggle night mode).

**Comment by jahirfiquitiva** [comment]
@afollestad 
Yeah, that's an option. Maybe you could include it in the library too.

**Comment by boswelja** [comment]
Ooh, that could be a nice idea
