### ISSUE TITLE
Animate color changes

### ISSUE THREAD

**Issue by ZinoKader** [afollestad/aesthetic#50]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of Aesthetic (see the README)
- [X] I have given my issue description title
- [X] I have read over the documentation (before asking questions on how to do something).

First of all, I would like to commend you on this fantastic library, really good work here! This is a feature request for building in an animated color change. As of now, it can be implemented by applying a new theme repeatedly, but that's a costly operation as far as I'm aware.

**Comment by boswelja** [comment]
We would have to change each items color individually, rather than recreating the activity on theme / color changes. I'm not sure if @afollestad would want to do that though

**Comment by afollestad** [comment]
@boswelja recreating activities is only necessary if you modify `.activityTheme(int)`. Otherwise, color updates are emitted through Rx observers.

**Comment by ZinoKader** [comment]
@boswelja This functionality would logically only apply to color changes which don't restart the activity, and those are set individually as far as I'm aware.

**Comment by boswelja** [comment]
@afollestad ooh, I thought the activity was recreated on any change. Seeing as that is the case, I can look into it if you're busy

**Comment by boswelja** [comment]
If we are going to add this, I suggest we have a method we can use to enable / disable animating changes. I have a few ideas on this:
* `animateColorChanges(boolean animate)` which would globally toggle color transitions, or
* `animateColorChanges(boolean animate, int duration)` to allow user-configurable transition duration (if set to 0, use default duration).
* Or we could add an extra boolean variable to the end of `primaryColor()` and `accentColor()` to allow animating individual colors, with a new method called `animationDuration(int duration)` to allow changing the duration manually.
I think the last method would be best, but in the end, it's up to you @afollestad :)

**Comment by timusus** [comment]
The question I have about implementing this feature: 

- Should Aesthetic output all the intermediate color values over the duration of the animation (so all the various `Observables` will emit a sequence of color int values from the current color to the new color), or

- Should each UI element that subscribes to Aesthetic `Observables` have it's own implementation of the animation change? 

The former is an easier solution, but potentially involves much more overhead (emitting a whole bunch of color changes rapidly over the duration of the animation could result in a lot of heavy duty changes performed by the subscribers)

The latter is potentially more efficient but also requires animations to be implemented in a lot of different `View` classes. `Views` which are automatically subscribed to theme changes (background color changes) are not currently subclassed by Aesthetic, so animations will have to be held somewhere to animate those changes as well.
