### ISSUE TITLE
Support AppCompatPreferenceActivity

### ISSUE THREAD

**Issue by AndreaCioccarelli** [afollestad/aesthetic#51]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of Aesthetic (see the README)
- [X] I have given my issue description title
- [X] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.6`
 - Device OS version: `7.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `S6 edge`

Also, **please wrap Java and Logcats with syntax highlighting:**

```java
public class SettingsPrefActivity extends AppCompatPreferenceActivity {
    private static final String TAG = SettingsPrefActivity.class.getSimpleName();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        Aesthetic.attach(this); // MUST come before super.onCreate(...)
        super.onCreate(savedInstanceState);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        getFragmentManager().beginTransaction().replace(android.R.id.content, new MainPreferenceFragment()).commit();
    }
}
```

![schermata 2017-07-15 alle 13 32 13](https://user-images.githubusercontent.com/23010471/28239035-41940e1c-6962-11e7-890f-97c1fe029a75.png)

###### Reproduction Steps
Create an AppCompatPreferenceActivity and try to set up Aesthetic

###### Expected Result
Not sure about it, but it should work also for Settings Activity

###### Actual Result
It actually doesn't support AppCompatPreferenceActivity

**Comment by afollestad** [comment]
I don't think this class exists anymore in the Support Library. I'm unable to find it with research.

https://developer.android.com/topic/libraries/support-library/packages#v7-preference
