### ISSUE TITLE
Gradle DSL method not found: 'implementation()' 

### ISSUE THREAD

**Issue by noman20** [afollestad/aesthetic#52]
Error:(41, 0) Gradle DSL method not found: 'implementation()' Possible causes:<ul><li>The project 'Filzilal ul Quran' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0). <a href="fixGradleElements">Upgrade plugin to version 2.3.2 and sync project</a></li><li>The project 'Filzilal ul Quran' may be using a version of Gradle that does not contain the method. <a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin. <a href="apply.gradle.plugin">Apply Gradle plugin</a></li> #52

**Comment by boswelja** [comment]
Very detailed.. please fill out the rest of the information

**Comment by MenosGrante** [comment]
Are you trying to use Gradle 4?

**Comment by boswelja** [comment]
So trying to use Gradle 4 features.. they only work in Android studio 3.0 Canary afaik
