### ISSUE TITLE
Remove dependency off of RxJava2

### ISSUE THREAD

**Issue by jaredsburrows** [afollestad/aesthetic#53]
Can you please not use RxJava directly in this project or can you product a library for RxJava 1 support?

**Comment by afollestad** [comment]
Sorry, no. You will need to migrate to Rx2 or use RxInterop.

**Comment by jaredsburrows** [comment]
Why have a library rely on many other libraries?

I guess as an alternative I can use: https://github.com/garretyoder/Colorful.

**Comment by boswelja** [comment]
_When people don't understand that upgrading stuff is better_

**Comment by jaredsburrows** [comment]
> When people don't understand that upgrading stuff is bette

@boswelja  I understand that upgrading is good. It's hard to move an entire application at once just to use a library to change your applications theme. Plus my question was never answered, why would rely on such a large library just to toggle shared preferences?

**Comment by afollestad** [comment]
Shared Preferences is the least of what Rx is really used for.

**Comment by jaredsburrows** [comment]
@afollestad Relax. You both are taking this the wrong way. I simply wanted a small library to handle theme changes. I found one.
