### ISSUE TITLE
Add ColorPickerPreference

### ISSUE THREAD

**Issue by Cilenco** [afollestad/aesthetic#55]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

It would be great to have preference which can be added to PreferenceScreens to simply let the user choose their prefered color and not only do this by code.

**Comment by afollestad** [comment]
This is out of scope of this library.
