### ISSUE TITLE
AlertDialog layout does not use theme values

### ISSUE THREAD

**Issue by TheNightmanCodeth** [afollestad/aesthetic#57]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of Aesthetic (see the README)
- [X] I have given my issue description title
- [X] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.7`
 - Device OS version: `7.1.2`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S6`

Using latest Aesthetic version, the views in my DialogActivity don't use the appropriate color values

Also, **please wrap Java and Logcats with syntax highlighting:**

```java
        val alertDialog: AlertDialog.Builder = AlertDialog.Builder(MainActivity@this)
        val dialogView = View.inflate(applicationContext, R.layout.add_class_dialog, null)

        alertDialog.setView(dialogView)
        alertDialog.setTitle(getString(R.string.add_class_dialog_title))
        alertDialog.setCancelable(true)
```
```xml
<EditText
        android:id="@+id/new_class_dialog_location"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:backgroundTint="?android:textColorPrimary"
        android:inputType="textCapWords"
        android:textColorHint="?android:textColorPrimary"
        android:hint="@string/location"/>

    <Button
        android:id="@+id/new_class_dialog_time_picker_button"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textColor="@color/white"
        android:text="@string/time"
        android:backgroundTint="?android:colorAccent" />
```
 
###### Reproduction Steps
Use `Aesthetic.isFirstTime()` to set theme values (same as R.style.default).
Create an AlertDialog with a custom view using `?android:attr` values for colors
Change theme colors with aesthetic

###### Expected Result
The button background and EditText background/hint color should match the values set by aesthetic

###### Actual Result
The dialog only uses the first start values. If the values are changed, the changes are not reflected in the AlertDialog.

I will add that the colors for the title text and positive/negative buttons on the dialog do change with aesthetic `colorAccent` and `textColorPrimary` values

**Comment by afollestad** [comment]
I haven't observed this problem.
