### ISSUE TITLE
Allow to set light and dark colors for icons or use the right values from Material Design guidelines

### ISSUE THREAD

**Issue by jahirfiquitiva** [afollestad/aesthetic#6]
From what I have seen, the library currently uses black and white for icons, but that's a limitation.

1. If the library aims to comply with material design guidelines, these are the values that should be used:

<table>
<tr><td rowspan="2">Icons</td><td colspan="3">Light background</td><td colspan="3">Dark background</td></tr>
<tr><td>Color</td><td>Opacity</td><td>Result in HEX</td><td>Color</td><td>Opacity</td><td>Result in HEX</td></tr>
<tr><td>Active</td><td>Black <code>#000000</code></td><td>54%</td><td><code>#8a000000</code></td><td>White <code>#ffffff</code></td><td>100%</td><td><code>#ffffffff</code></td></tr>
<tr><td>Inactive</td><td>Black <code>#000000</code></td><td>38%</td><td><code>#61000000</code></td><td>White <code>#ffffff</code></td><td>50%</td><td><code>#80ffffff</code></td></tr>
</table>

_Taken from [here](https://material.io/guidelines/style/color.html#color-usability)._

2. If not, can you please add options to set the default icons colors so one can change them?

Thanks.

**Comment by afollestad** [comment]
Correct defaults are used in 0.0.6. Added an `iconTitleColor` setting.

**Comment by jahirfiquitiva** [comment]
@afollestad Thank you 😁
