### ISSUE TITLE
Ignore tag doesn't work in RecyclerView items

### ISSUE THREAD

**Issue by hugocastelani** [afollestad/aesthetic#74]
- [ ✓ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ✓ ] I have verified that I am using the latest version of Aesthetic (see the README)
- [ ✓ ] I have given my issue description title
- [ ✓ ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.7`
 - Device OS version: `7.1.2`
 - Device Manufacturer: `LG`
 - Device Name: `G2`
 
###### Reproduction Steps
Set item's `android:tag=":aesthetic_ignore"` in XML or `view.setTag(":aesthetic_ignore")` in Java. I also tried adding tag to RecyclerView.

###### Expected Result
Aesthetic ignore view.

###### Actual Result
Aesthetic keep theming view.

**Comment by SmartDroidDeveloper** [comment]
Hey @HugoCastelani same issue i am facing inside listview item, 
Have you found any solution? then please let me know.

**Comment by HugoCastelani** [comment]
Sorry, I didn't.

**Comment by afollestad** [comment]
Applying the tag to the views you want to ignore in your list item layouts works just fine, just tried it. It can't go on the parent view, currently, it has to go on the exact view.
