### ISSUE TITLE
clone and build latest project ,simple can't tint menu icon

### ISSUE THREAD

**Issue by iota9star** [afollestad/aesthetic#76]
- [✔] I have verified there are no duplicate active or recent bugs, questions, or requests
- [✔] I have verified that I am using the latest version of Aesthetic (see the README)
- [✔] I have given my issue description title
- [✔] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.7`
 - Device OS version: `7.1.2`
 - Device Manufacturer: `oneplus`
 - Device Name: `3`

![screenshot_20171231-190057_01](https://user-images.githubusercontent.com/21272154/34461103-190c7576-ee5d-11e7-8f24-bfbb16425358.jpg)

**Comment by gonemad** [comment]
Adding this.icon =icon; in AestheticActionMenuItemView.java should fix the issue

'''java
@Override
  public void setIcon(final Drawable icon) {
    super.setIcon(icon);
    **this.icon = icon;**
    // We need to retrieve the color again here.
    // For some reason, without this, a transparent color is used and the icon disappears
    // when the overflow menu opens.
    Aesthetic.get()
        .colorIconTitle(null)
        .observeOn(AndroidSchedulers.mainThread())
        .take(1)
        .subscribe(
            new Consumer<ActiveInactiveColors>() {
              @Override
              public void accept(@NonNull ActiveInactiveColors colors) {
                invalidateColors(colors);
              }
            },
            onErrorLogAndRethrow());
  }
'''

could we get this fix and a new release of the lib?  0.4.7 was 8 months ago and doesnt include some pretty big fixes like 

https://github.com/afollestad/aesthetic/commit/b6cb5df0e41043263cae91fb69ad109a44cf7d31#diff-4755da0dfe15641e3c5846ffb39f8370

**Comment by gonemad** [comment]
actually the following seems to resolve this issue, still fixes #5, and doesnt cause another issue i was running into where the icon would flash if I would clear the menu and inflate a new menu into it (think swiping tabs in a viewpager.. each tab with its own menu)

```java
@Override
  public void setIcon(final Drawable icon) {    
    this.icon = icon;
    // We need to retrieve the color again here.
    // For some reason, without this, a transparent color is used and the icon disappears
    // when the overflow menu opens.
    Aesthetic.get()
        .colorIconTitle(null)    
        .take(1)
        .subscribe(
            new Consumer<ActiveInactiveColors>() {
              @Override
              public void accept(@NonNull ActiveInactiveColors colors) {
                invalidateColors(colors);
              }
            },
            onErrorLogAndRethrow());
  }
```

**Comment by iota9star** [comment]
@gonemad thanks , i'm sorry my poor english. i try using them, but i got a problem like
 `// We need to retrieve the color again here.   
// For some reason, without this, a transparent color is used and the icon disappears    
// when the overflow menu opens.`
if i inflate menu every time, its cost is too much

**Comment by gonemad** [comment]
odd.. doesnt happen for me

**Comment by gonemad** [comment]
Unless I'm missing a commit the bug still exists in the code base.....

**Comment by afollestad** [comment]
https://github.com/afollestad/aesthetic/releases/tag/0.5.0
