### ISSUE TITLE
Borderless button text color is wrong

### ISSUE THREAD

**Issue by tcqq** [afollestad/aesthetic#81]
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.7`
 - Device OS version: `8.1.0`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

@afollestad Borderless button text color is white now, should use accent color is right.

And missing click ripple.

```
<Button
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="Button"
    style="@style/Widget.AppCompat.Button.Borderless"/>
```

**Comment by tcqq** [comment]
@afollestad Check these images.
![image](https://user-images.githubusercontent.com/10644057/39029309-ad7cfb82-448d-11e8-88f8-c2e0bee80442.png)
![image](https://user-images.githubusercontent.com/10644057/39029331-c80a9bc6-448d-11e8-963a-7c359e826eea.png)

**Comment by afollestad** [comment]
Hmm, that requires knowing that the button is borderless which can't really be determined with the style res ID safely.

**Comment by afollestad** [comment]
https://github.com/afollestad/aesthetic/releases/tag/0.5.0
