### ISSUE TITLE
how to set error text color using this library ... 

### ISSUE THREAD

**Issue by shobhan1595** [afollestad/aesthetic#83]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Aesthetic (see the README)
- [ ] I have given my issue description title
- [ ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.x.x.x`
 - Device OS version: `7.1.2`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

Also, **please wrap Java and Logcats with syntax highlighting:**

```java
System.out.println("Hello, world!");
```

```gradle
java.lang.RuntimeException: Oh no, an unknown error occurred!
    at com.example.helloworld.MainActivity.onCreate()
    at com.example.helloworld.idkHey()
```

```xml
<RelativeLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content" />
```

**Comment by afollestad** [comment]
There's not enough information for this to be an issue.
