### ISSUE TITLE
How to use latest 0.5.0 in java project?

### ISSUE THREAD

**Issue by hedongfu** [afollestad/aesthetic#84]
aesthetic has new tag 0.5.0, but it totally re-written in Kotlin. 
The integration is different:
Use  class MainActivity : AestheticActivity() instead of MainActivity extends AestheticActivity.
This is Kotlin style, is this mean we can't use 0.5.0 in Android Java project?
Thanks!

**Comment by afollestad** [comment]
They're both JVM languages, so there should be no problems with interop.
