### ISSUE TITLE
Application onTerminate not called on production device

### ISSUE THREAD

**Issue by kkalisz** [afollestad/aesthetic#9]
According do android documentation onTermiante callback is invoked only emulated environments.
[https://developer.android.com/reference/android/app/Application.html#onTerminate()](https://developer.android.com/reference/android/app/Application.html#onTerminate())

Invoking Aesthetic.destroy() on oTerminate() will have no effect since onTermiante is not invoked.
From the other hand when appliaction is killed all resources are released. I personally think that this Aesthetic.destroy() should be invoked in other place if

**Comment by afollestad** [comment]
No longer required in 0.0.6.
