### ISSUE TITLE
ImageView tinting

### ISSUE THREAD

**Issue by DeweyReed** [afollestad/aesthetic#91]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue a description and title
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.5.3`
 - Device OS version: `8.1.0` and `9`
 - Device Manufacturer: `Emulator`
 - Device Name: `Emulator`

Great library. But I encounter something weird.

This is a simple XML.

```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <ImageView
        android:layout_width="256dp"
        android:layout_height="256dp"
        android:layout_gravity="center"
        android:scaleType="fitXY"
        app:srcCompat="@drawable/ic_check"
        android:tint="?colorAccent" />
</FrameLayout>
```

Then, 

```kotlin
val layout = findViewById<ViewGroup>(R.id.layout)
layout.addView(LayoutInflater.from(this)
  .inflate(R.layout.layout_empty_view, layout, false))
```
 
###### Reproduction Steps
Create a XML layout, create the view using `LayoutInfalter` and add it to a `ViewGroup`

###### Expected Result
The `ImageView` should use the accent color from Aesthetic.

###### Actual Result
No, it uses original color that is declared in the activity theme.

I've read through README and many issues but have no clue what to do to make it work.

**Comment by afollestad** [comment]
This isn't an issue with the `LayoutInflater`. Aesthetic doesn't support image view tints at the moment.

**Comment by afollestad** [comment]
https://github.com/afollestad/aesthetic/releases/tag/0.6.0
