### ISSUE TITLE
Bottom Navigation always using BottomNavBgMode.BLACK_WHITE_AUTO

### ISSUE THREAD

**Issue by jordyamc** [afollestad/aesthetic#95]
- [ X ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ X ] I have verified that I am using the latest version of Aesthetic (see the README)
- [ X ] I have given my issue a description and title
- [ X ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.7.0`
 - Device OS version: `8.1`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto G5 Plus`

Bottom navigation always using BottomNavBgMode.BLACK_WHITE_AUTO
And sometimes Text using primary text instead of accent

```kotlin
Aesthetic.config {
                    activityTheme(R.style.Theme_AppCompat_NoActionBar)
                    isDark(true)
                    colorPrimary(primaryColor(context))
                    colorStatusBarAuto()
                    colorNavigationBarAuto()
                    colorAccentRes(accentColor(context))
                    navigationViewMode(NavigationViewMode.SELECTED_ACCENT)
                    bottomNavigationBackgroundMode(BottomNavBgMode.PRIMARY)
                    bottomNavigationIconTextMode(BottomNavIconTextMode.SELECTED_ACCENT)
                }
```
![photo_2018-09-15_18-18-02](https://user-images.githubusercontent.com/6831873/45591324-5701fd00-b915-11e8-9f95-3006499194ec.jpg)
![photo_2018-09-15_18-30-19](https://user-images.githubusercontent.com/6831873/45591326-70a34480-b915-11e8-888f-9a01cf2deabd.jpg)
 

###### Reproduction Steps
Use `bottomNavigationBackgroundMode(BottomNavBgMode.PRIMARY)`

###### Expected Result
Bottom navigation use primary color

###### Actual Result
Bottom navigation use black/white

**Comment by afollestad** [comment]
Hmmm, I'm not able to reproduce this. 

<img src="https://user-images.githubusercontent.com/1820165/45591500-8f034300-b909-11e8-8dff-bf17d9d7b141.png" width="250" />

**Comment by jordyamc** [comment]
I found a clue, i was using this in my bottom nav
```xml
app:background="?colorPrimary"
app:itemBackground="?colorPrimary"
app:itemIconTint="@drawable/bottom_state"
app:itemTextColor="@drawable/bottom_state"
```

bottom_state.xml
```xml
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="?colorAccent" android:state_checked="true"/>
    <item android:color="@android:color/white"/>
</selector>
```

After removing it, the bottom nav is now using correct background

**Comment by jordyamc** [comment]
I found some more errors
-Bottom nav not changing when colorAccent changes
-Radio buttons from List preference not theming
![giphy](https://user-images.githubusercontent.com/6831873/45603249-e4b21b00-b9ef-11e8-81db-8883ca163c1a.gif)

**Comment by afollestad** [comment]
That'd belong in a separate issue
