### ISSUE TITLE
Can I override theming of my views without using the :aesthetic_ignore tag?

### ISSUE THREAD

**Issue by jordyamc** [afollestad/aesthetic#98]
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/aesthetic/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have verified that I am using the latest version of Aesthetic (see the README).
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/aesthetic/blob/master/README.md) (before asking questions on how to do something).

---

**If this is a feature request, you can clear everything below.**

##### Include the following:

 - Affected device(s): Motorola Moto G5 Plus

Is it a way to change the color of views (text, background, hint, etc) without using `:aesthetic_ignore` tag?

Like finding views inside libraries view to change colors

```kotlin
val searchEdit = searchView.findViewById(R.id.edittext_search) as EditText
searchEdit.inputType = InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS
searchEdit.textColor = ContextCompat.getColor(this, android.R.color.black)
searchEdit.hintTextColor = ContextCompat.getColor(this, android.R.color.darker_gray)
```
 
---
 
##### Reproduction Steps
Try to change colors of a view without `:aesthetic_ignore` tag
##### Expected Result
The colors change
##### Actual Result
The colors don't change

**Comment by jordyamc** [comment]
I use a library that can take colors directly from xml but using Aesthetic changes the EditView to primary dark/light colors, but the background is always white so when my app is in dark mode the text ends in white with white background

**Comment by afollestad** [comment]
Yes, it uses the configurable text color primary or text color secondary values by default, unless your XML specifies something different.

**Comment by jordyamc** [comment]
So in cases like this when you use a library that wrap some views instead of extending a single one?
